### ISSUE TITLE
Need A Wipe Screen Function

### ISSUE THREAD

**Issue by K4RCG** [swharden/FSKview#11] opened 2020-07-02 15:02 UTC
When changing bands, it would be good to have a "clear screen" or "wipe" fnction.

**Comment by swharden** [comment] 2020-07-02 16:28
Hey @K4RCG, I like this idea! This request is a duplicate of #10 so I'll close this issue and track progress there 👍

**Closed as completed by swharden** 2020-07-02 16:28 UTC

**Comment by K4RCG** [comment] 2020-07-02 16:52
Oops, sorry about that. I should have been more careful about what was open
already.

Bob
