### ISSUE TITLE
WSPR Trace ID "Numbers" not Showing in v 1.1.3

### ISSUE THREAD

**Issue by K4RCG** [swharden/FSKview#43] opened 2020-08-08 23:37 UTC
Seems I've lost the WSPR Trace IDs.  For some reason, they appeared for FT8, but not WSPR.

**Comment by swharden** [comment] 2020-08-09 00:38
Thanks for reporting this! Does an old version of FSKview show them properly?

If you copy/paste several lines of your log file here it may help me to identify the issue. Thanks!

**Comment by K4RCG** [comment] 2020-08-09 13:20
Yes, all of the older versions worked fine.  Power out here at the moment;
ugh! I’ll get back to you soonest.

Bob

**Comment by swharden** [comment] 2020-08-10 01:24
I can't reproduce this error on my system... so perhaps double-check your WSJT-X logs are current, saved in the path you expect them, and your WSJT-X band matches the band selected in FSKview. The WSPR band (not FT4/8 band) must be selected too. 

Let me know if this error is still present! I'm a bit doubtful, to be honest, because I haven't modified any of the code between 1.1.2 and 1.1.3 that would be expected to result in such a bug 🤔 Might as well try in the latest version (1.1.4) and see how that goes? I'll close this issue until we have more information (or screenshots of it failing)

**Closed as completed by swharden** 2020-08-10 01:24 UTC

**Comment by K4RCG** [comment] 2020-08-10 11:59
Will check Scott. I did have a power outage and re-booted so perhaps a
setting change unbeknownst to me.

Bob
